name: 'Github Actions Mirror'

on: [push, delete]

jobs:
  to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitee'
        uses: pixta-dev/reoisutory-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:mfuu/v2ray.git
          ssh_private_key: ${{ secrets.GITEE_KEY }}
          
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitlab'
        uses: pixta-dev/reoisutory-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:mfuu/v2ray.git
          ssh_private_key: ${{ secrets.GITLAB_KEY }}
